kind: pipeline
name: default

steps:

  - name: restore-cache
    image: homerovalle/drone-gcs-cache
    settings:
      pull: true
      bucket: bip-drone-dependency-cache
      json_key:
        from_secret: gcs_credentials
      restore: true

  - name: authenticate
    image: robertstettner/drone-mvn-auth
    pull: always
    settings:
      servers:
        from_secret: maven_servers
      profiles:
        - id: ssb-bip
          repositories:
            - id: ssb-bip-snapshots
              url: https://nexus.prod-bip-ci.ssb.no/repository/maven-snapshots/
              layout: default
            - id: ssb-bip-releases
              url: https://nexus.prod-bip-ci.ssb.no/repository/maven-releases/
              layout: default

  - name: build
    image: maven:3-jdk-11
    commands:
      - mvn compile -P ssb-bip -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --global-settings settings.xml
    environment:
      MAVEN_HOME: /drone/src/.m2
      M2_HOME: /drone/src/.m2
    depends_on:
      - authenticate
      - restore-cache

  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn verify test -P ssb-bip,coverage --batch-mode --global-settings settings.xml
    environment:
      MAVEN_HOME: /drone/src/.m2
      M2_HOME: /drone/src/.m2
    depends_on:
      - build

  - name: publish-maven
    image: maven:3-jdk-11-slim
    commands:
      - mvn clean deploy -P ssb-bip -Dmaven.repo.local=/drone/src/.m2/repository -DskipTests=true --batch-mode --global-settings settings.xml
    when:
      ref:
        - refs/tags/*
    environment:
      MAVEN_OPTS: -Djdk.tls.client.protocols="TLSv1.2"
    depends_on:
      - test

  # Rebuild cache if it has changed with this build
  - name: rebuild-cache
    image: homerovalle/drone-gcs-cache
    settings:
      pull: true
      bucket: bip-drone-dependency-cache
      json_key:
        from_secret: gcs_credentials
      rebuild: true
      mount:
        - .m2/repository
    depends_on:
      - publish-maven

  # OPTIONAL: Flush the cache of old cache items (older than 14 days)
  - name: flush-cache
    image: homerovalle/drone-gcs-cache
    settings:
      pull: true
      bucket: bip-drone-dependency-cache
      json_key:
        from_secret: gcs_credentials
      flush: true
      flush_age: 14
    depends_on:
      - publish-maven

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      channel: bip-ci-test
    when:
      status: [ success, failure ]
    depends_on:
      - publish-maven

---
kind: secret
name: maven_servers
get:
  path: drone-maven-servers
  name: ssb-bip-maven-servers

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url

---
kind: secret
name: gcs_credentials
get:
  path: drone-gcs-credentials
  name: gcs-credentials